### ISSUE TITLE
Sound loop breaks without user input

### ISSUE THREAD

**Issue by dmrib** [machinegrooving/spacecadet#5]
During development I realized that sometimes Chrome would not play the audio correctly, giving the following error on console:

```The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.```

This happens because we are currently playing the audio without a effective way of giving the option to our users of knowing that a track will be played on that website.

https://github.com/processing/p5.js-website/issues/396
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

We must change the behavior of the sketch to only play audio after some kind of user input.

**Comment by dmrib** [comment]
I just had a good idea to solve this:

What if instead of starting the terrain scene at the sketch execution, we create a `Start` button on a kind of welcome screen that would handle this event? 

This will also be probably useful to make us able to collect the webcam stream from the user.

**Comment by anothergoldenmonkey** [comment]
Seems like a valid solution. 👍
